from setuptools import setup, find_packages

setup(
    name="vnpy-grid",
    version="0.1.0",
    description=(
        "VN.PY grid-trading toolkit with backtest utilities and strategies"
    ),
    author="AutoGenerated",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.11",
    install_requires=[
        "vnpy>=2.4.0",
    ],
    include_package_data=True,
    zip_safe=False,
)
